"""Trend detection and clinical alerting for longitudinal ECG monitoring.

Computes EWMA-smoothed trends and z-score deviations from a patient baseline,
then generates clinical alerts when metrics exceed configurable thresholds.
"""

from __future__ import annotations

import dataclasses

import numpy as np
import pandas as pd


# Metrics tracked for trend detection — subset of compute_session_metrics output
# Metrics displayed in trend charts (all session metrics worth visualizing)
DISPLAY_METRICS = [
    'mean_hr_bpm',
    'sdnn_ms',
    'pvc_burden_pct',
    'sve_burden_pct',
    'rr_cv_pct',
    'mean_qrs_width_ms',
    'pause_count_2s',
    'max_rr_interval_s',
    'mean_r_amplitude',
]

# Metrics that trigger alerts — excludes RMSSD and pNN50 because rising ectopic
# burden fragments the N-N interval pool, causing these metrics to trend in the
# wrong direction (up instead of down) as a selection artifact.
TRACKED_METRICS = [
    'mean_hr_bpm',
    'sdnn_ms',
    'pvc_burden_pct',
    'sve_burden_pct',
    'rr_cv_pct',
    'mean_qrs_width_ms',
    'pause_count_2s',
    'max_rr_interval_s',
    'mean_r_amplitude',
]


# Alert rules: direction indicates which way is clinically concerning.
# "rising" = alert when metric increases; "falling" = alert when it decreases;
# "both" = alert on deviation in either direction.
ALERT_RULES: dict[str, dict] = {
    'mean_hr_bpm': {
        'direction': 'both',
        'warn': 2.0,
        'danger': 3.0,
        'unit': 'bpm',
        'interpretation_rising': 'Elevated heart rate — may indicate HF decompensation, infection, or dehydration',
        'interpretation_falling': 'Developing bradycardia — may indicate conduction disease or medication toxicity',
    },
    'sdnn_ms': {
        'direction': 'falling',
        'warn': 2.0,
        'danger': 3.0,
        'unit': 'ms',
        'interpretation_falling': 'Declining HRV — suggests autonomic deterioration',
    },
    'pvc_burden_pct': {
        'direction': 'rising',
        'warn': 2.0,
        'danger': 3.0,
        'unit': '%',
        'interpretation_rising': 'Increasing PVC burden — risk of PVC-induced cardiomyopathy if sustained >10%',
    },
    'sve_burden_pct': {
        'direction': 'rising',
        'warn': 2.0,
        'danger': 3.0,
        'unit': '%',
        'interpretation_rising': 'Increasing SVE burden — atrial irritability, AF precursor',
    },
    'rr_cv_pct': {
        'direction': 'rising',
        'warn': 2.0,
        'danger': 3.0,
        'unit': '%',
        'interpretation_rising': 'Increasing RR irregularity — suggests developing atrial fibrillation',
    },
    'mean_qrs_width_ms': {
        'direction': 'rising',
        'warn': 2.0,
        'danger': 3.0,
        'unit': 'ms',
        'interpretation_rising': 'QRS widening — progressive conduction disease or bundle branch block',
    },
    'pause_count_2s': {
        'direction': 'rising',
        'warn': 2.0,
        'danger': 3.0,
        'unit': 'pauses',
        'interpretation_rising': 'Emerging pauses — suggests AV conduction disease',
    },
    'max_rr_interval_s': {
        'direction': 'rising',
        'warn': 2.0,
        'danger': 3.0,
        'unit': 's',
        'interpretation_rising': 'Lengthening maximum RR interval — conduction disease or sinus arrest',
    },
    'mean_r_amplitude': {
        'direction': 'falling',
        'warn': 2.0,
        'danger': 3.0,
        'unit': 'mV',
        'interpretation_falling': 'Declining R-wave amplitude — possible pericardial effusion or cardiomyopathy',
    },
}


@dataclasses.dataclass
class Alert:
    """A single clinical alert fired by the trend engine."""

    session: int
    metric: str
    severity: str           # 'warning', 'danger', or 'forecast'
    value: float
    baseline_mean: float
    baseline_std: float
    z_score: float
    direction: str          # 'rising' or 'falling'
    interpretation: str
    unit: str


@dataclasses.dataclass
class Forecast:
    """Projected trend line for a single metric at a specific session.

    Generated by fitting quadratic regression on observed data up to that
    session and projecting forward over a fixed horizon.
    """

    metric: str
    fit_session: int                    # session at which the forecast was made
    projected_sessions: list[float]     # future session indices
    projected_values: list[float]       # projected metric values
    ci_lower: list[float]              # lower 95% prediction interval
    ci_upper: list[float]              # upper 95% prediction interval
    warn_crossing: float | None        # session where projection crosses warning threshold
    danger_crossing: float | None      # session where projection crosses danger threshold
    prob_warn: float                   # P(crossing warning threshold within horizon)
    prob_danger: float                 # P(crossing danger threshold within horizon)


def compute_baseline_stats(
    df_sessions: pd.DataFrame,
    n_baseline: int = 3,
) -> dict[str, tuple[float, float]]:
    """Compute per-metric baseline mean and std from the first N sessions.

    Args:
        df_sessions: DataFrame with one row per session and metric columns.
        n_baseline: Number of initial sessions to use as baseline.

    Returns:
        Dict of metric_name -> (mean, std). Std is floored at a small positive
        value to avoid division by zero for perfectly stable metrics.
    """
    baseline_rows = df_sessions.head(n_baseline)
    stats = {}
    for metric in DISPLAY_METRICS:
        if metric not in df_sessions.columns:
            continue
        values = baseline_rows[metric].dropna()
        if len(values) == 0:
            continue
        mean = float(values.mean())
        std = float(values.std(ddof=1)) if len(values) > 1 else 0.0
        # Floor std to avoid infinite z-scores for perfectly stable baseline
        std = max(std, abs(mean) * 0.01, 1e-6)
        stats[metric] = (mean, std)
    return stats


def compute_trends(
    df_sessions: pd.DataFrame,
    n_baseline: int = 3,
    ewma_span: int = 3,
) -> pd.DataFrame:
    """Compute EWMA-smoothed values and z-scores for all tracked metrics.

    Args:
        df_sessions: DataFrame from run_scenario (one row per session).
        n_baseline: Number of initial sessions for baseline computation.
        ewma_span: EWMA span parameter (number of sessions).

    Returns:
        Long-format DataFrame with columns:
        [session, metric, raw_value, ewma_value, z_score, baseline_mean,
         baseline_std]
    """
    stats = compute_baseline_stats(df_sessions, n_baseline)
    rows = []

    for metric in DISPLAY_METRICS:
        if metric not in df_sessions.columns or metric not in stats:
            continue
        mean, std = stats[metric]
        raw = df_sessions[metric].values
        ewma = pd.Series(raw).ewm(span=ewma_span, min_periods=1).mean().values

        for i in range(len(raw)):
            val = raw[i]
            z = (val - mean) / std if not np.isnan(val) else np.nan
            rows.append({
                'session': int(df_sessions['session'].iloc[i]),
                'metric': metric,
                'raw_value': float(val) if not np.isnan(val) else None,
                'ewma_value': float(ewma[i]),
                'z_score': float(z) if not np.isnan(z) else None,
                'baseline_mean': mean,
                'baseline_std': std,
            })

    return pd.DataFrame(rows)


def detect_alerts(
    df_trends: pd.DataFrame,
    n_baseline: int = 3,
) -> list[Alert]:
    """Scan trend data for metric deviations that trigger clinical alerts.

    Only sessions after the baseline window are evaluated for alerts.

    Args:
        df_trends: Output of compute_trends().
        n_baseline: Number of baseline sessions (alerts start after these).

    Returns:
        List of Alert objects sorted by session, then severity (danger first).
    """
    alerts = []

    for metric, rule in ALERT_RULES.items():
        metric_data = df_trends[df_trends['metric'] == metric]
        if metric_data.empty:
            continue

        for _, row in metric_data.iterrows():
            if row['session'] < n_baseline:
                continue
            z = row['z_score']
            if z is None or np.isnan(z):
                continue

            direction = rule['direction']
            fired = False
            severity = None
            alert_direction = None

            if direction == 'rising':
                if z >= rule['danger']:
                    fired, severity, alert_direction = True, 'danger', 'rising'
                elif z >= rule['warn']:
                    fired, severity, alert_direction = True, 'warning', 'rising'
            elif direction == 'falling':
                if z <= -rule['danger']:
                    fired, severity, alert_direction = True, 'danger', 'falling'
                elif z <= -rule['warn']:
                    fired, severity, alert_direction = True, 'warning', 'falling'
            elif direction == 'both':
                if abs(z) >= rule['danger']:
                    fired = True
                    severity = 'danger'
                    alert_direction = 'rising' if z > 0 else 'falling'
                elif abs(z) >= rule['warn']:
                    fired = True
                    severity = 'warning'
                    alert_direction = 'rising' if z > 0 else 'falling'

            if fired:
                interp_key = f'interpretation_{alert_direction}'
                interpretation = rule.get(interp_key, '')
                alerts.append(Alert(
                    session=int(row['session']),
                    metric=metric,
                    severity=severity,
                    value=row['raw_value'],
                    baseline_mean=row['baseline_mean'],
                    baseline_std=row['baseline_std'],
                    z_score=float(z),
                    direction=alert_direction,
                    interpretation=interpretation,
                    unit=rule.get('unit', ''),
                ))

    # Sort: by session, then danger before warning
    severity_order = {'danger': 0, 'warning': 1}
    alerts.sort(key=lambda a: (a.session, severity_order.get(a.severity, 2)))
    return alerts


def _fit_linear_forecast(
    sessions: np.ndarray,
    values: np.ndarray,
    n_forward: int,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Fit linear regression (y = a + bx) and project forward.

    Returns:
        (future_sessions, predicted, ci_lower, ci_upper)
    """
    n = len(sessions)
    if n < 3:
        return np.array([]), np.array([]), np.array([]), np.array([])

    # Build design matrix: [1, x]
    X = np.column_stack([np.ones(n), sessions])

    # OLS: beta = (X'X)^-1 X'y
    try:
        XtX_inv = np.linalg.inv(X.T @ X)
    except np.linalg.LinAlgError:
        return np.array([]), np.array([]), np.array([]), np.array([])

    beta = XtX_inv @ (X.T @ values)
    fitted = X @ beta
    residuals = values - fitted

    # Residual standard error
    dof = n - 2  # n - (intercept + slope)
    if dof > 0:
        s_e = np.sqrt((residuals ** 2).sum() / dof)
    else:
        s_e = 0.0

    # Project forward
    last_session = int(sessions[-1])
    future = np.arange(last_session + 1, last_session + 1 + n_forward, dtype=float)
    X_future = np.column_stack([np.ones(n_forward), future])
    predicted = X_future @ beta

    # 95% prediction interval
    # PI = z * s_e * sqrt(1 + x_new' (X'X)^-1 x_new)
    if s_e > 0 and dof > 0:
        pi_width = np.array([
            1.96 * s_e * np.sqrt(1.0 + x_row @ XtX_inv @ x_row)
            for x_row in X_future
        ])
    else:
        pi_width = np.zeros_like(future)

    return future, predicted, predicted - pi_width, predicted + pi_width


def _find_threshold_crossing(
    future_sessions: np.ndarray,
    projected_values: np.ndarray,
    threshold: float,
    direction: str,
) -> float | None:
    """Find the interpolated session where projection crosses a threshold.

    Args:
        direction: 'rising' means crossing when value goes above threshold;
                   'falling' means crossing when value goes below threshold.

    Returns:
        Interpolated session index, or None if no crossing.
    """
    for i in range(len(projected_values)):
        if direction == 'rising' and projected_values[i] >= threshold:
            if i == 0:
                return float(future_sessions[0])
            # Linear interpolation between i-1 and i
            v0, v1 = projected_values[i - 1], projected_values[i]
            s0, s1 = future_sessions[i - 1], future_sessions[i]
            if abs(v1 - v0) < 1e-12:
                return float(s0)
            frac = (threshold - v0) / (v1 - v0)
            return float(s0 + frac * (s1 - s0))
        elif direction == 'falling' and projected_values[i] <= threshold:
            if i == 0:
                return float(future_sessions[0])
            v0, v1 = projected_values[i - 1], projected_values[i]
            s0, s1 = future_sessions[i - 1], future_sessions[i]
            if abs(v1 - v0) < 1e-12:
                return float(s0)
            frac = (threshold - v0) / (v1 - v0)
            return float(s0 + frac * (s1 - s0))
    return None


def _compute_crossing_probability(
    predicted: np.ndarray,
    ci_lower: np.ndarray,
    ci_upper: np.ndarray,
    threshold: float,
    direction: str,
) -> float:
    """Compute max P(crossing threshold) over all projected sessions.

    Uses the prediction interval to estimate the standard deviation of the
    forecast distribution at each future session, then computes
    P(crossing) = 1 - Φ((threshold - predicted) / σ) for rising metrics, or
    P(crossing) = Φ((threshold - predicted) / σ) for falling metrics.

    Returns the maximum probability across the horizon.
    """
    from scipy.stats import norm

    if len(predicted) == 0:
        return 0.0

    # Recover prediction std from the 95% CI: width = 2 * 1.96 * σ
    ci_width = ci_upper - ci_lower
    pred_std = ci_width / (2 * 1.96)
    # Floor to avoid division by zero
    pred_std = np.maximum(pred_std, 1e-9)

    if direction == 'rising':
        # P(value >= threshold) = 1 - Φ((threshold - predicted) / σ)
        probs = 1.0 - norm.cdf((threshold - predicted) / pred_std)
    else:
        # P(value <= threshold) = Φ((threshold - predicted) / σ)
        probs = norm.cdf((threshold - predicted) / pred_std)

    return float(np.max(probs))


def detect_forecast_alerts(
    df_trends: pd.DataFrame,
    actual_alerts: list[Alert],
    n_baseline: int = 3,
    min_fit_points: int = 3,
    forecast_horizon: int = 20,
    prob_threshold: float = 0.70,
) -> tuple[list[Alert], dict[str, list[Forecast]]]:
    """Generate probability-based forecast alerts for trending metrics.

    At each session (after sufficient post-baseline data), fits a quadratic
    regression on all observed data so far, projects forward over a fixed
    horizon, and computes P(crossing threshold) from the prediction interval.
    Emits a forecast alert when probability exceeds the confidence threshold.

    Forecasts retrain every session — evolving confidence is tracked in the
    Forecast objects for visualization. Multiple forecast alerts can be emitted
    for the same metric as confidence evolves.

    Forecast alerts are suppressed once an actual alert (warning/danger) fires.

    Args:
        df_trends: Output of compute_trends().
        actual_alerts: Output of detect_alerts().
        n_baseline: Number of baseline sessions.
        min_fit_points: Minimum post-baseline data points before forecasting.
        forecast_horizon: Fixed number of sessions to project ahead.
        prob_threshold: Probability threshold to emit forecast alert (0-1).

    Returns:
        Tuple of (forecast_alerts, forecasts_by_metric).
        forecast_alerts: List of Alert objects with severity='forecast'.
        forecasts_by_metric: Dict of metric -> list of Forecast objects
            (one per session, for chart rendering and drill-down).
    """
    forecast_alerts: list[Alert] = []
    forecasts_by_metric: dict[str, list[Forecast]] = {}

    for metric, rule in ALERT_RULES.items():
        metric_data = df_trends[df_trends['metric'] == metric].sort_values('session')
        if metric_data.empty:
            continue

        sessions_all = metric_data['session'].values
        values_all = metric_data['raw_value'].values
        baseline_mean = metric_data['baseline_mean'].iloc[0]
        baseline_std = metric_data['baseline_std'].iloc[0]

        direction = rule['direction']
        warn_thresh_hi = baseline_mean + rule['warn'] * baseline_std
        warn_thresh_lo = baseline_mean - rule['warn'] * baseline_std
        danger_thresh_hi = baseline_mean + rule['danger'] * baseline_std
        danger_thresh_lo = baseline_mean - rule['danger'] * baseline_std

        if direction == 'rising':
            warn_thresh, danger_thresh = warn_thresh_hi, danger_thresh_hi
            cross_dir = 'rising'
        elif direction == 'falling':
            warn_thresh, danger_thresh = warn_thresh_lo, danger_thresh_lo
            cross_dir = 'falling'
        else:
            # 'both' — determine direction from post-baseline trend
            post_mask = sessions_all >= n_baseline
            if post_mask.sum() >= 2:
                post_vals = values_all[post_mask]
                trend_dir = 'rising' if post_vals[-1] > post_vals[0] else 'falling'
            else:
                continue
            if trend_dir == 'rising':
                warn_thresh, danger_thresh = warn_thresh_hi, danger_thresh_hi
                cross_dir = 'rising'
            else:
                warn_thresh, danger_thresh = warn_thresh_lo, danger_thresh_lo
                cross_dir = 'falling'

        forecasts = []

        for end_idx in range(n_baseline + min_fit_points, len(sessions_all) + 1):
            current_session = int(sessions_all[end_idx - 1])

            fit_sessions = sessions_all[:end_idx].astype(float)
            fit_values = values_all[:end_idx].astype(float)

            valid = ~np.isnan(fit_values)
            if valid.sum() < min_fit_points:
                continue

            future, predicted, ci_lo, ci_hi = _fit_linear_forecast(
                fit_sessions[valid], fit_values[valid], forecast_horizon)

            if len(future) == 0:
                continue

            # Compute crossing probabilities
            prob_warn = _compute_crossing_probability(
                predicted, ci_lo, ci_hi, warn_thresh, cross_dir)
            prob_danger = _compute_crossing_probability(
                predicted, ci_lo, ci_hi, danger_thresh, cross_dir)

            # Find point-estimate crossings for reference
            warn_cross = _find_threshold_crossing(
                future, predicted, warn_thresh, cross_dir)
            danger_cross = _find_threshold_crossing(
                future, predicted, danger_thresh, cross_dir)

            forecast = Forecast(
                metric=metric,
                fit_session=current_session,
                projected_sessions=future.tolist(),
                projected_values=predicted.tolist(),
                ci_lower=ci_lo.tolist(),
                ci_upper=ci_hi.tolist(),
                warn_crossing=warn_cross,
                danger_crossing=danger_cross,
                prob_warn=prob_warn,
                prob_danger=prob_danger,
            )
            forecasts.append(forecast)

            # Emit forecast alert only when danger probability crosses threshold
            if prob_danger < prob_threshold:
                continue
            severity_label = 'danger'
            prob_val = prob_danger

            current_val = float(fit_values[valid][-1])
            current_z = ((current_val - baseline_mean) / baseline_std
                         if baseline_std > 0 else 0.0)

            interp_key = f'interpretation_{cross_dir}'
            base_interp = rule.get(interp_key, '')
            interpretation = (
                f"Forecast: {base_interp.lower()} "
                f"P({severity_label} within {forecast_horizon} sessions) = "
                f"{prob_val:.0%}."
            )

            forecast_alerts.append(Alert(
                session=current_session,
                metric=metric,
                severity='forecast',
                value=current_val,
                baseline_mean=baseline_mean,
                baseline_std=baseline_std,
                z_score=float(current_z),
                direction=cross_dir,
                interpretation=interpretation,
                unit=rule.get('unit', ''),
            ))

        if forecasts:
            forecasts_by_metric[metric] = forecasts

    forecast_alerts.sort(key=lambda a: a.session)
    return forecast_alerts, forecasts_by_metric


def summarize_alerts(
    alerts: list[Alert],
    df_sessions: pd.DataFrame,
) -> str:
    """Generate a human-readable summary of alerts and metric changes.

    Args:
        alerts: List of Alert objects (may include severity='forecast').
        df_sessions: Session metrics DataFrame.

    Returns:
        Multi-line summary string.
    """
    if not alerts:
        return "No clinical alerts triggered. All metrics within baseline range."

    n_danger = sum(1 for a in alerts if a.severity == 'danger')
    n_warning = sum(1 for a in alerts if a.severity == 'warning')
    n_forecast = sum(1 for a in alerts if a.severity == 'forecast')
    n_sessions = len(df_sessions)

    parts = []
    if n_danger:
        parts.append(f"{n_danger} danger")
    if n_warning:
        parts.append(f"{n_warning} warning")
    if n_forecast:
        parts.append(f"{n_forecast} forecast")
    lines = [f"Over {n_sessions} sessions: {', '.join(parts)} alert(s)."]
    lines.append("")

    # Summarize key metric changes (first vs last session)
    first = df_sessions.iloc[0]
    last = df_sessions.iloc[-1]
    alerted_metrics = {a.metric for a in alerts}

    for metric in TRACKED_METRICS:
        if metric not in alerted_metrics:
            continue
        if metric not in df_sessions.columns:
            continue
        v0, v1 = first.get(metric), last.get(metric)
        if v0 is None or v1 is None or np.isnan(v0) or np.isnan(v1):
            continue
        unit = ALERT_RULES.get(metric, {}).get('unit', '')
        lines.append(f"  {metric}: {v0:.1f} -> {v1:.1f} {unit}")

    return "\n".join(lines)
